version: '3.9'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl
      - ./tools:/var/www/html
    restart: unless-stopped
