listen=YES

# Disable anonymous login
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Enable directory messages
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# Jail local users
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

# Configure Allowed users
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Configure passive mode ports
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009

# Resolve passive address
pasv_addr_resolve=YES
pasv_address=usogukpi.42.fr

# Container-friendly
seccomp_sandbox=NO
