listen=YES

anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# Jail
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

# Allowed users
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Passive ports for Docker/NAT
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009

pasv_addr_resolve=YES
pasv_address=usogukpi.42.fr

# Container-friendly (prevents some sandbox-related child deaths)
seccomp_sandbox=NO
