# Default port
port 6379

# Network & Security
bind 127.0.0.1 172.18.0.5
protected-mode no

# Memory Management 
maxmemory 256mb
maxmemory-policy allkeys-lru

# Data Persistence Settings
appendonly no